# Generated by Django 4.2.6 on 2023-10-20 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('school', models.CharField(choices=[('Arts and Sciences', 'Arts And Sci'), ('Business', 'Business'), ('Leadership and Public Policy', 'Politics'), ('Commerce', 'Commerce'), ('Architecture', 'Architecture'), ('Education and Human Development', 'Edu'), ('Engineering and Applied Science', 'Engr'), ('Law', 'Law'), ('Medicine', 'Med'), ('Nursing', 'Nurse')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudySpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=100)),
                ('school', models.CharField(choices=[('Arts and Sciences', 'Arts And Sci'), ('Business', 'Business'), ('Leadership and Public Policy', 'Politics'), ('Commerce', 'Commerce'), ('Architecture', 'Architecture'), ('Education and Human Development', 'Edu'), ('Engineering and Applied Science', 'Engr'), ('Law', 'Law'), ('Medicine', 'Med'), ('Nursing', 'Nurse')], max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('submission_date', models.DateField(default=django.utils.timezone.now)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('noise_level', models.IntegerField(default=0)),
                ('occupancy', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=256)),
                ('published_date', models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 20, 16, 21, 56, 852673, tzinfo=datetime.timezone.utc))),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.studyspot')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studyspot',
            constraint=models.UniqueConstraint(fields=('building', 'room_number'), name='unique_location'),
        ),
    ]
