# Generated by Django 4.2.6 on 2023-10-20 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 20, 16, 22, 47, 547344, tzinfo=datetime.timezone.utc)),
        ),
    ]
