# Generated by Django 4.2.6 on 2023-11-02 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_remove_studyspot_school_studyspot_lat_studyspot_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 2, 21, 12, 16, 227339, tzinfo=datetime.timezone.utc)),
        ),
    ]
