# Generated by Django 4.2.6 on 2023-11-02 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0007_alter_review_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 2, 21, 32, 59, 48554, tzinfo=datetime.timezone.utc)),
        ),
    ]
