# Generated by Django 4.2.6 on 2023-11-02 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0015_alter_review_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 2, 22, 52, 24, 584324, tzinfo=datetime.timezone.utc)),
        ),
    ]
