# Generated by Django 4.2.6 on 2023-11-05 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0018_alter_review_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='review',
            name='building',
            field=models.CharField(default='Default Building', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='comfort',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='crowdedness',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='hours',
            field=models.CharField(blank=True, choices=[('Open Late', 'Open Late'), ('24/7', '24/7'), ('Normal Hours', 'Normal Hours'), ('Closes early', 'Closes early')], default='Normal Hours', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='parking',
            field=models.CharField(blank=True, choices=[('Street', 'Street'), ('Garage', 'Garage'), ('None', 'None')], default='Garage', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='room_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='noise_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='occupancy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 5, 8, 29, 46, 496163, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='studyspot',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='studyspot',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
