# Generated by Django 4.2.6 on 2023-11-05 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0019_remove_review_submitted_by_review_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 5, 8, 30, 25, 858175, tzinfo=datetime.timezone.utc)),
        ),
    ]
