# Generated by Django 4.2.6 on 2023-11-05 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0020_alter_review_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 5, 8, 32, 24, 910938, tzinfo=datetime.timezone.utc)),
        ),
    ]
