# Generated by Django 4.2.6 on 2023-11-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0021_alter_review_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='review',
            name='building',
            field=models.CharField(default='', max_length=100),
        ),
    ]
