# Generated by Django 4.2.5 on 2023-11-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0022_remove_review_published_date_alter_review_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='parking',
            field=models.CharField(blank=True, choices=[('Street', 'Street'), ('Garage', 'Garage'), ('Parking lot', 'Parking lot'), ('None', 'None')], default='Garage', max_length=20, null=True),
        ),
    ]
