# Generated by Django 4.2.6 on 2023-11-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0023_alter_review_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
