# Generated by Django 4.2.6 on 2023-11-13 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0024_review_is_approved'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studyspot',
            name='unique_location',
        ),
    ]
