# Generated by Django 4.2.6 on 2023-11-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0026_alter_review_comfort_alter_review_crowdedness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='noise_level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, null=True),
        ),
    ]
